# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-27 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answare', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='check')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('answare', models.ManyToManyField(to='cleanapp.Answare')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanapp.CityModel')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='question',
            name='answare_type',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='reports',
            name='questions',
            field=models.ManyToManyField(default=False, to='cleanapp.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cleanapp.Title'),
            preserve_default=False,
        ),
    ]
