# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-27 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0003_question_answare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answare',
            old_name='Answare',
            new_name='asd',
        ),
    ]
