# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-27 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0006_auto_20170827_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answare',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cleanapp.Answare'),
        ),
    ]
