# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0008_auto_20170828_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='answare',
        ),
        migrations.AlterField(
            model_name='question',
            name='answare',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answare',
        ),
    ]
