# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0009_auto_20170828_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answare',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
