# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0011_auto_20170829_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answare',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='answare',
            field=models.ManyToManyField(default=None, to='cleanapp.Answare'),
        ),
    ]
