# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0012_auto_20170829_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answare',
            field=models.ManyToManyField(to='cleanapp.Answare'),
        ),
    ]
