# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0014_auto_20170830_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answare_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
