# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0017_auto_20170831_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reports',
            name='questions_answers',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='questions_images',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
