# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0018_auto_20170831_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answare',
            field=models.ManyToManyField(null=True, related_name='answare', to='cleanapp.Answare'),
        ),
    ]
