# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 22:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleanapp', '0024_auto_20170831_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
