# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0026_auto_20170913_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='City_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanapp.CityModel', unique=True),
        ),
    ]
