# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0027_auto_20170913_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='City_Name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='citymodel',
            name='City_Name',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
