# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-20 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0031_auto_20170918_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillImge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='bills/%Y/%m/%d/%s')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='uploads/No_image_3x4.svg.png', null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
