# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0032_auto_20170920_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answare',
            name='answer',
            field=models.TextField(),
        ),
    ]
