# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0033_auto_20170922_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answare',
        ),
        migrations.AddField(
            model_name='question',
            name='answare',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.DeleteModel(
            name='Answare',
        ),
    ]
