# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0034_auto_20170923_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='billimge',
            name='notes',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='billimge',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
