# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0035_auto_20170923_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billimge',
            name='image',
            field=models.ImageField(upload_to='bills/%Y/%m/%d/'),
        ),
    ]
