# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-24 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0036_auto_20170923_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answare',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
