# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-25 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0037_auto_20170924_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='perm',
            field=models.BooleanField(default=False),
        ),
    ]
