# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 13:04
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0042_auto_20170928_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billimge',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='bills/%Y/%m/%d/'),
        ),
    ]
