# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-02 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0044_weekarrangemorning'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekArrangeEvning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.CharField(max_length=200)),
                ('day2', models.CharField(max_length=200)),
                ('day3', models.CharField(max_length=200)),
                ('day4', models.CharField(max_length=200)),
                ('day5', models.CharField(max_length=200)),
                ('day6', models.CharField(max_length=200)),
                ('day7', models.CharField(max_length=200)),
            ],
        ),
    ]
