# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-02 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0045_weekarrangeevning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeekArrangeEvning',
        ),
        migrations.RenameField(
            model_name='weekarrangemorning',
            old_name='day1',
            new_name='day1m',
        ),
        migrations.RenameField(
            model_name='weekarrangemorning',
            old_name='day2',
            new_name='day2m',
        ),
        migrations.RenameField(
            model_name='weekarrangemorning',
            old_name='day3',
            new_name='day3m',
        ),
        migrations.RenameField(
            model_name='weekarrangemorning',
            old_name='day4',
            new_name='day4m',
        ),
        migrations.RenameField(
            model_name='weekarrangemorning',
            old_name='day5',
            new_name='day5m',
        ),
        migrations.RenameField(
            model_name='weekarrangemorning',
            old_name='day6',
            new_name='day6m',
        ),
        migrations.RenameField(
            model_name='weekarrangemorning',
            old_name='day7',
            new_name='day7m',
        ),
        migrations.AddField(
            model_name='weekarrangemorning',
            name='day1e',
            field=models.CharField(default='ריק', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekarrangemorning',
            name='day2e',
            field=models.CharField(default='ריק', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekarrangemorning',
            name='day3e',
            field=models.CharField(default='ריק', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekarrangemorning',
            name='day4e',
            field=models.CharField(default='ריק', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekarrangemorning',
            name='day5e',
            field=models.CharField(default='ריק', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekarrangemorning',
            name='day6e',
            field=models.CharField(default='ריק', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekarrangemorning',
            name='day7e',
            field=models.CharField(default='ריק', max_length=200),
            preserve_default=False,
        ),
    ]
