# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-02 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanapp', '0046_auto_20171002_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekarrangemorning',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cleanapp.CityModel'),
            preserve_default=False,
        ),
    ]
