#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.http import HttpResponse
from reportlab.lib.enums import TA_JUSTIFY,TA_RIGHT,TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.pdfbase import pdfmetrics
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import PageBreak, Paragraph, Spacer, Image
from .models import Reports,Question,Title
from reportlab.lib.units import inch
import json

def report(request, reportid):
    report = Reports.objects.get(id=reportid)
    testid = str(report.pub_date)
    basename = str("דוח ניקיון")
    filename = "_".join([basename, testid])
    doc = SimpleDocTemplate(filename +'.pdf', pagesize=letter, rightMargin=72,leftMargin=72,topMargin=18,bottomMargin=18)
    logo = "/Users/user/Desktop/DjangoProjects/yesPlanet/cleanapp/static/Asset 1@2x.png"
    im = Image(logo, 4 * inch, 1 * inch)
    Story = []
    Story.append(im)
    city = report.city
    city = city.City_Name
    pdfmetrics.registerFont(TTFont("carmelitbold",'/Users/user/Desktop/DjangoProjects/yesPlanet/cleanapp/static/fonts/Nehama.ttf'))
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Justify', alignment=TA_RIGHT,fontName='carmelitbold'))
    styles.add(ParagraphStyle(name='mytitle', alignment=TA_CENTER,fontName='carmelitbold'))
    ptext = '<font size=12>%s</font>' %city
    Story.append(Paragraph(ptext, styles["mytitle"]))
    Story.append(PageBreak())
    titles = Title.objects.order_by('id')
    anses = report.questions_answers
    anses=json.loads(anses)
    for titel in titles:
        questions = Question.objects.filter(title=titel)
        temptitel=str(titel)
        temptitel=temptitel[::-1]
        ptext = '<font size=18>%s</font>' % temptitel
        Story.append(Paragraph(ptext, styles["mytitle"]))
        Story.append(Spacer(1, 12))
        for q in questions:
            qid = q.id
            if q.title == titel:
                q = str(q)
                q = q[::-1]
                qid = str(qid)
                answer=anses[qid]
                if answer=='1':
                    ansimage = "/Users/user/Desktop/DjangoProjects/yesPlanet/cleanapp/static/images/Screen Shot 2017-09-04 at 21.05.20.png"
                elif answer=='2':
                    ansimage = "/Users/user/Desktop/DjangoProjects/yesPlanet/cleanapp/static/images/Screen Shot 2017-09-04 at 21.05.32.png"
                elif answer=='3':
                    ansimage = "/Users/user/Desktop/DjangoProjects/yesPlanet/cleanapp/static/images/Screen Shot 2017-09-04 at 21.05.41.png"
                elif answer=='4':
                    ansimage = "/Users/user/Desktop/DjangoProjects/yesPlanet/cleanapp/static/images/Screen Shot 2017-09-04 at 21.05.41.png"
                else:
                    pass
                ptext = "<font size=12>%s</font>"%q
                im = Image(ansimage, 1 * inch, 0.5 * inch)
                Story.append(im)
                Story.append(Paragraph(ptext, styles["Justify"]))
                Story.append(Spacer(1, 12))
        Story.append(PageBreak())
    doc.build(Story)
    return HttpResponse("<html>Tanks</html>")
